// <auto-generated />
namespace SilberScarves.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class addforeignKeytocusteomr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addforeignKeytocusteomr));
        
        string IMigrationMetadata.Id
        {
            get { return "201403081855316_add foreignKey to custeomr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
